---
authors: ["Julian Easterling <julian@julianscorner.com>"]
build_ignore:
  - README.md
  - build.cmd
  - .gitignore
  - .vscode
  - .github
  - .ansible-lint
  - .gitattributes
  - .yamllint
  - .editorconfig
description: Runbook that will validate a host can ping another host on the Internet.
homepage: https://github.com/dcjulian29/ansible-runbook-ping_internet
issues: https://github.com/dcjulian29/ansible-runbook-ping_internet/issues
license: ["Apache-2.0"]
name: ping_internet
namespace: dcjulian29
readme: https://github.com/dcjulian29/ansible-runbook-ping_internet/blob/main/README.md
repository: https://github.com/dcjulian29/ansible-runbook-ping_internet
tags:
  - ping_internet
  - dcjulian29
version: 0.9.0
